# Generated by Django 5.2 on 2026-03-05 01:57

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("slug", models.SlugField(unique=True)),
                ("order_index", models.IntegerField(default=0)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "labels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "coordinates_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "coordinates_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "google_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("google_reviews_count", models.IntegerField(blank=True, null=True)),
                ("price_double_room", models.IntegerField(blank=True, null=True)),
                ("price_quad_room", models.IntegerField(blank=True, null=True)),
                ("show_on_homepage", models.BooleanField(default=False)),
                ("agoda_slug", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "booking_slug",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("klook_slug", models.CharField(blank=True, max_length=100, null=True)),
                ("kkday_slug", models.CharField(blank=True, max_length=100, null=True)),
                ("photo_main", models.URLField(blank=True, null=True)),
                ("photo_1", models.URLField(blank=True, null=True)),
                ("photo_2", models.URLField(blank=True, null=True)),
                ("photo_3", models.URLField(blank=True, null=True)),
                ("photo_4", models.URLField(blank=True, null=True)),
                ("photo_5", models.URLField(blank=True, null=True)),
                ("photo_6", models.URLField(blank=True, null=True)),
                ("photo_7", models.URLField(blank=True, null=True)),
                ("photo_8", models.URLField(blank=True, null=True)),
                ("photo_9", models.URLField(blank=True, null=True)),
                ("photo_10", models.URLField(blank=True, null=True)),
                ("real_1", models.URLField(blank=True, max_length=500, null=True)),
                ("real_2", models.URLField(blank=True, max_length=500, null=True)),
                ("real_3", models.URLField(blank=True, max_length=500, null=True)),
                ("real_4", models.URLField(blank=True, max_length=500, null=True)),
                ("real_5", models.URLField(blank=True, max_length=500, null=True)),
                ("real_6", models.URLField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hotels",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("slug", models.SlugField(unique=True)),
                ("category", models.SlugField(blank=True, null=True)),
                ("order_index", models.IntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
                ("featured_prefix", models.BooleanField(default=False)),
                (
                    "featured_suffix",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "labels",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("slug", models.SlugField(unique=True)),
                ("parent_slug", models.SlugField(blank=True, null=True)),
                ("order_index", models.IntegerField(default=0)),
                (
                    "map_center_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "map_center_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "map_zoom",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "places",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlaceDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.JSONField(blank=True, null=True)),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "seo_keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "place_details",
                "managed": False,
            },
        ),
    ]
